### PR TITLE
Password verification.

### PR DESCRIPTION
**Pull request by RyoshiKayo**

### CODE REVIEW

**Comment by Pitu** [comment]
Until there's a specific page or button to toggle from Login to Register, I won't implement this. Can't have a Login form with 2 password inputs *just in case they want to register*

**Comment by alucard0134** [comment]
i mean crawl already did so

**Comment by alucard0134** [comment]
wait nope

**Comment by RyoshiKayo** [comment]
I'm not sure what you mean @Pitu , this is just to verify the person knows the password they're setting in the admin settings.

**Comment by Pitu** [comment]
What I'm saying is that the way you made it is that the password check field will be present at all times, even if you are only trying to log in and not register. So, displaying an extra field for the login form which will only be used when registering, is not something that I want to have.

**Comment by iCrawl** [comment]
But this is on the dashboard, not on the auth where you login or register.

**Comment by Pitu** [comment]
Next time I won't reply the second I wake up. Derp. Sounds good, I'll try it local and then merge if everything's okay.

**Pull request merged**
